db.driver=com.mysql.cj.jdbc.Driver
db.url=${DB_URL}
db.user=${DB_USERNAME}
db.pass=${DB_PASSWORD}


# Configuraci�n del pool
hikari.maximumPoolSize=15
hikari.minimumIdle=2
hikari.connectionTimeout=10000
hikari.idleTimeout=300000
hikari.maxLifetime=600000
